# Generated by Django 3.1.5 on 2021-01-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
